ewmac16_64:
    function: systems.provided.rules.ewmac.ewmac
    data:
        - "rawdata.get_daily_prices"
        - "rawdata.daily_returns_volatility"
    other_args: 
        Lfast: 16
        Lslow: 64